ci:
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.4"
    hooks:
      - id: fix-ligatures
      - id: fix-smartquotes
      - id: fix-spaces
      - id: forbid-bidi-controls

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: "v0.6.13"
    hooks:
      - id: cmake-format
        additional_dependencies: [pyyaml]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v17.0.6"
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.4"
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
