name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
        compiler:
          - gcc
          - gcc-10
          - gcc-11
          - gcc-12
          - gcc-13
          - gcc-14
          - llvm
          - llvm-10
          - llvm-11
          - llvm-12
          - llvm-13
          - llvm-14
          - llvm-15
          - llvm-16
          - llvm-17
          - llvm-18
        preset:
          - release
        include:
          - runner: ubuntu-latest
            compiler: gcc
            preset: debug
          - runner: ubuntu-latest
            compiler: llvm
            preset: debug
      fail-fast: false
    name: ${{ matrix.runner }} • ${{ matrix.compiler }} • ${{ matrix.preset }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: true
      - uses: aminya/setup-cpp@v0.37.0
        with:
          compiler: ${{ matrix.compiler }}
      - uses: lukka/get-cmake@v3.30.1
      - uses: lukka/run-vcpkg@v11.5
      - uses: lukka/run-cmake@v10.7
        with:
          workflowPreset: ${{ matrix.preset }}

  macos:
    strategy:
      matrix:
        runner:
          - macos-latest
        xcode:
          - latest-stable
          - latest
          - "14.3.1"
          - "15.4"
          - "16.0"
        preset:
          - release
        include:
          - runner: macos-12
            xcode: "13.1"
            preset: release
          - runner: macos-12
            xcode: "14.2"
            preset: release
      fail-fast: false
    name: ${{ matrix.runner }} • xcode=${{ matrix.xcode }} • ${{ matrix.preset }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: true
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: lukka/get-cmake@v3.30.1
      - uses: lukka/run-vcpkg@v11.5
      - uses: lukka/run-cmake@v10.7
        with:
          workflowPreset: ${{ matrix.preset }}

  windows:
    strategy:
      matrix:
        runner:
          - windows-latest
        compiler:
          - msvc
          - msvc-2019
          - msvc-2022
        preset:
          - release
      fail-fast: false
    name: ${{ matrix.runner }} • ${{ matrix.compiler }} • ${{ matrix.preset }}
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
          submodules: true
      - uses: aminya/setup-cpp@v0.37.0
        with:
          compiler: ${{ matrix.compiler }}
      - uses: lukka/get-cmake@v3.30.1
      - uses: lukka/run-vcpkg@v11.5
      - uses: lukka/run-cmake@v10.7
        with:
          workflowPreset: ${{ matrix.preset }}
